version: 2

project_name: ssh-portal
dist: ./output

# Gitea configuration
gitea_urls:
  api: https://git.apps.windmill.it/api/v1
  download: https://git.apps.windmill.it

before:
  hooks:
    - go mod tidy

builds:
  - id: ssh-portal
    main: ./cmd/ssh-portal/main.go
    env:
      - CGO_ENABLED=0        # turn off cgo for easy cross-compile
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X ssh-portal/internal/version.Version={{.Version}}
      - -X ssh-portal/internal/version.Commit={{.ShortCommit}}
      - -X ssh-portal/internal/version.Date={{.CommitDate}}      
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
  

archives:
  - formats: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE*
universal_binaries:
  - id: ssh-portal                # matches the build id above
    replace: true            # replace the darwin slices with one fat binary

nfpms:
  - id: ssh-portal-rpm
    package_name: ssh-portal
    vendor: "WMLX.it"
    homepage: https://github.com/wmlx/ssh-portal
    maintainer: "Lele Forzani <lele@wmlx.it>"
    description: |
      SSH Portal - A tool for managing SSH connections and sessions.
    license: "Proprietary"
    formats:
      - rpm
      - deb
    bindir: /usr/bin
    # RPM-specific settings
    rpm:
      group: Applications/System
      compression: lzma
      summary: SSH connection and session management tool
    contents:
      - src: README.md
        dst: /usr/share/doc/ssh-portal/README.md
      - src: LICENSE*
        dst: /usr/share/doc/ssh-portal/
    # Dependencies for runtime
    recommends:
      - openssh-client

uploads:
  - name: gitea_rpm
    # Upload RPM and DEB packages
    exts:
      - rpm

    # Treat them as "archives" (includes Linux packages generated by nFPM)
    mode: archive

    # Use the exact Gitea upload URL (no filename at the end)
    custom_artifact_name: true
    target: https://git.apps.windmill.it/api/packages/{{ .Env.UPLOAD_GITEA_RPM_USERNAME }}/rpm/{{ .ProjectName }}/upload

    # Authentication via environment variables
    # name=gitea_rpm => UPLOAD_GITEA_RPM_USERNAME / UPLOAD_GITEA_RPM_SECRET
    # These are automatically loaded by the release script from ~/.config/tea/config.yml
